# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grupo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('foraneaGrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grupo.Grupo')),
                ('tareasEstudiante', models.ManyToManyField(to='Tarea.Tarea')),
                ('usuarioEstudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
