# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tema', '0001_initial'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tituloTarea', models.CharField(max_length=50)),
                ('descripcionTarea', models.TextField(max_length=200)),
                ('fechaLimite', models.DateTimeField(default=datetime.datetime.now)),
                ('rutaArchivo', models.FileField(blank=True, null=True, upload_to='Tarea/Profesor/')),
                ('logrosTarea', models.TextField(blank=True, max_length=200, null=True)),
                ('foraneaCurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                ('foraneaTema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tema.Tema')),
            ],
        ),
    ]
