# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('cedula', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('codigoprofesor', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
