# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('idGrado', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
