# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MateriaGrado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('idTema', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombreTema', models.CharField(max_length=20)),
                ('descripcionTema', models.TextField(max_length=200)),
                ('foraneaMateriaGrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MateriaGrado.MateriaGrado')),
            ],
        ),
    ]
